if [ -f /etc/bashrc ]; then
  . /etc/bashrc
fi

if [[ -s "$HOME/.rvm/scripts/rvm" ]]  ; then 
  source "$HOME/.rvm/scripts/rvm" ; 
fi

SCRIPT_PATH="${BASH_SOURCE[0]}"
if [[ -h $SCRIPT_PATH ]] ; then
  while [[ -h $SCRIPT_PATH ]] ; do SCRIPT_PATH=`readlink $SCRIPT_PATH`; done
fi

SCRIPT_DIR=`dirname $SCRIPT_PATH`

# Load host-specific settings, if any
if [[ -d $SCRIPT_DIR/`hostname` ]]; then
  HOST_SETTINGS_DIR=$SCRIPT_DIR/`hostname`
elif [[ -d $HOME/.`hostname` ]]; then
  HOST_SETTINGS_DIR=$HOME/.`hostname`
fi

if [[ -d $HOST_SETTINGS_DIR ]] ; then
  echo "Sourcing files found in $HOST_SETTINGS_DIR..."
  for file in $HOST_SETTINGS_DIR/*; do source $file; done
fi

PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting
