#!/bin/bash
SOCKET_PATH=/tmp/tmux_shareds
SESSION=pairing
USER=goldstar
MACHINE=${1:-`hostname`}
TMUX=/usr/local/bin/tmux

CMD=<<EOF
   $TMUX -S $SOCKET_PATH new-session -s $SESSION || \
   $TMUX -S $SOCKET_PATH attach -t $SESSION
EOF

case "$1" in
    start|serve) $TMUX -S $SOCKET_PATH new-session -s $SESSION; ;;
    list) $TMUX -S $SOCKET_PATH list-sessions; ;;
    attach) $TMUX -S $SOCKET_PATH attach; ;;
    *) ssh $USER@$MACHINE -t $CMD; ;;
esac
