#!/bin/sh

#  UPDATED: 01-22-2009

#  HandBrakeCLI-batch.sh is a script to batch execute the HandBrakeCLI.
#  This script is based upon the MediaForkCLI-batch.sh.

# Usage: HandBrakeCLI-batch.sh [options]
#
#  arg1:   inputSearchDir=<string>   Set input directory to process all DVDs in it (example: ~/Movies/Batch Rip) "
#  arg2:   outputDir=<string>        Set output directory for all output files (example: ~/Movies/Batch Encode) "
#  arg3:   fileType=<string>         Set the file type: .mp4, .avi, .omg, .mkv, .m4v (example: .m4v) "
#  arg4:   minTrackTime=<number>     Set the minimum time (mins) of the track/s to encode (example: 30) "
#  arg5:   toolArgs=<string>         Set the HandBrakeCLI encode settings (example: -2 -w 640) "

# Revision history:
# 0.20070329.0 - initial release
# 0.20081125.0 - revised for HandBrakeCLI
# 0.20090122.0 - fixed problem with spaces in the directory tree


#############################################################################
# globals

# const global variables
scriptName=`basename "$0"`
scriptVers="2.0"
scriptPID=$$
saveDVDinfo=1       # the dvd track info is also saved as txt file when on
skipDuplicates=1    # if this option is off (-0),
                    # the new output files will overwrite existing files
                    E_BADARGS=65

                    # set the global variables to default
                    toolName="HandBrakeCLI"
                    toolPath="/Applications/$toolName"
                    toolTrackArgs="-t 0" # scans dvd title list for all tracks
                    inputSearchDir=$1    # set input search directory: "~/Movies/Batch Rip"
                    outputDir="$2"       # set output directory: "~/Movies/Batch Encode"
                    fileType="$3"        # set output container: .m4v, .mp4, .avi, .omg, .mkv
                    minTrackTime="$4"    # this is in minutes: "30"
                    toolArgs="$5"        # set handbrakecli encode settings: "-2 -w 640"

                    #############################################################################
                    # functions

                    verifyFindCLTool()
                    {
                        # attempt to find the HandBrakeCLI if the script toolPath is not good
                          if [ ! -x "$toolPath" ];
                              then
                                    toolPathTMP=`PATH=.:/Applications:/:/usr/bin:/usr/local/bin:$HOME:$PATH which $toolName | sed '/^[^\/]/d' | sed 's/\S//g'`
                                        
                                        if [ ! -z $toolPathTMP ]; then 
                                                toolPath=$toolPathTMP
                                                    fi
                                                      fi  
                                                    }

                                                    displayUsageExit()
                                                    {
                                                        echo "Usage: $scriptName [options]"
                                                          echo ""
                                                            echo "    -h, --help   Print help"
                                                              echo "    arg1:   inputSearchDir=<string>   Set input directory to process all DVDs in it (example: ~/Movies/Batch Rip) "
                                                                echo "    arg2:   outputDir=<string>        Set output directory for all output files (example: ~/Movies/Batch Encode) "
                                                                  echo "    arg3:   fileType=<string>         Set the file type: .mp4, .avi, .omg, .mkv, .m4v (example: .m4v) "
                                                                    echo "    arg4:   minTrackTime=<number>     Set the minimum time (mins) of the track/s to encode (example: 30) "
                                                                      echo "    arg5:   toolArgs=<string>         Set the HandBrakeCLI encode settings (example: -2 -w 640) "
                                                                        
                                                                        
                                                                        if [ -x "$toolPath" ];
                                                                            then
                                                                                  echo "   $toolName possible options"
                                                                                      mForkHelp=`$toolPath --help 2>&1`
                                                                                          mForkHelpPt=`printf "$mForkHelp" | egrep -v '( --input| --output| --help|Syntax: |^$)'`
                                                                                              printf "$mForkHelpPt\n"
                                                                                                else
                                                                                                      echo "    The options available to HandBrakeCLI except -o  and -i"
                                                                                                          if [ -e "$toolPath" ];
                                                                                                                then
                                                                                                                        echo "    ERROR: $toolName command tool is not setup to execute"
                                                                                                                              echo "    ERROR: attempting to use tool at $toolPath"
                                                                                                                                  else
                                                                                                                                          echo "    ERROR: $toolName command tool could not be found"
                                                                                                                                                echo "    ERROR: $toolName can be install in ./ /usr/local/bin/ /usr/bin/ ~/ or /Applications/"
                                                                                                                                                    fi
                                                                                                                                                      fi
                                                                                                                                                        
                                                                                                                                                        echo ""
                                                                                                                                                          
                                                                                                                                                          exit $E_BADARGS
                                                                                                                                                        }

                                                                                                                                                        getTrackListLongerThan()
                                                                                                                                                        {
                                                                                                                                                            # Two input arguments are are need. 
                                                                                                                                                              #   arg1 is the time in minutes selector
                                                                                                                                                                #   arg2 is the raw text stream from the track 0 call to HandBrake
                                                                                                                                                                  #   returns: a list of track numbers of tracks longer then the selector
                                                                                                                                                                    
                                                                                                                                                                    if [ $# -lt 2 ]; then
                                                                                                                                                                          return ""
                                                                                                                                                                            fi
                                                                                                                                                                              
                                                                                                                                                                              minTime="$1"
                                                                                                                                                                                shift
                                                                                                                                                                                  allTrackText="$*"
                                                                                                                                                                                    aReturn=""

                                                                                                                                                                                      trackList=`eval "echo \"$allTrackText\" | egrep '(^\+ title |\+ duration\:)' | sed -e 's/^[^+]*+ //'g -e 's/title \([0-9]*\):/\1-/'g -e 's/duration: //'g"`
                                                                                                                                                                                        
                                                                                                                                                                                        trackNumber=""
                                                                                                                                                                                          for aline in $trackList
                                                                                                                                                                                              do
                                                                                                                                                                                                    trackLineFlag=`echo $aline | sed 's/[0-9]*-$/-/'`
                                                                                                                                                                                                        if [ $trackLineFlag = "-" ];
                                                                                                                                                                                                              then
                                                                                                                                                                                                                      trackNumber=`echo $aline | sed 's/\([0-9]*\)-/\1/'`
                                                                                                                                                                                                                          else
                                                                                                                                                                                                                                  set -- `echo $aline | sed -e 's/(^[:0-9])//g' -e 's/:/ /g'`
                                                                                                                                                                                                                                        if [ $3 -gt 29 ];
                                                                                                                                                                                                                                                then let trackTime=($1*60)+$2+1
                                                                                                                                                                                                                                                        else let trackTime=($1*60)+$2
                                                                                                                                                                                                                                                                fi

                                                                                                                                                                                                                                                                      if [ $trackTime -gt $minTime ];
                                                                                                                                                                                                                                                                              then aReturn="$aReturn $trackNumber"
                                                                                                                                                                                                                                                                                      fi
                                                                                                                                                                                                                                                                                          fi
                                                                                                                                                                                                                                                                                            done
                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                              echo "$aReturn"
                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                            makeFullPath()
                                                                                                                                                                                                                                                                                            {
                                                                                                                                                                                                                                                                                                 aReturn=""
                                                                                                                                                                                                                                                                                                    currentPath=`pwd`
                                                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                                       if [ $# -gt 0 ]; then
                                                                                                                                                                                                                                                                                                               inPath="$*"
                                                                                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                                                                     # put full path in front of path if needed
                                                                                                                                                                                                                                                                                                                           aReturn=`echo "$inPath" | sed -e "s!~!$currentPath/!" -e "s!^./!$currentPath/!" -e "s!^\([^/]\)!$currentPath/\1!" -e "s!^../!$currentPath/../!"`
                                                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                                 # remove ../ from path - only goes 4 deep
                                                                                                                                                                                                                                                                                                                                       aReturn=`echo "$aReturn" | sed -e 's!/[^\.^/]*/\.\./!/!g' | sed -e 's!/[^\.^/]*/\.\./!/!g' | sed -e 's!/[^\.^/]*/\.\./!/!g' | sed -e 's!/[^\.^/]*/\.\./!/!g'`
                                                                                                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                                                                                             # cleanup by removing //
                                                                                                                                                                                                                                                                                                                                                   aReturn=`echo "$aReturn" | sed -e 's!//!/!g'`
                                                                                                                                                                                                                                                                                                                                                      fi
                                                                                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                                                         echo "$aReturn"
                                                                                                                                                                                                                                                                                                                                                       }

                                                                                                                                                                                                                                                                                                                                                       isPIDRunning()
                                                                                                                                                                                                                                                                                                                                                       {
                                                                                                                                                                                                                                                                                                                                                          aResult=0
                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                            if [ $# -gt 0 ]; then
                                                                                                                                                                                                                                                                                                                                                                  txtResult="`ps ax | egrep \"^[ \t]*$1\" | sed -e 's/.*/1/'`"
                                                                                                                                                                                                                                                                                                                                                                      if [ -z "$txtResult" ];
                                                                                                                                                                                                                                                                                                                                                                            then aResult=0
                                                                                                                                                                                                                                                                                                                                                                                  else aResult=1
                                                                                                                                                                                                                                                                                                                                                                                        fi
                                                                                                                                                                                                                                                                                                                                                                                          fi
                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                            echo $aResult
                                                                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                                                                          #############################################################################
                                                                                                                                                                                                                                                                                                                                                                                          # MAIN SCRIPT

                                                                                                                                                                                                                                                                                                                                                                                          # initialization functions
                                                                                                                                                                                                                                                                                                                                                                                          verifyFindCLTool

                                                                                                                                                                                                                                                                                                                                                                                          # fix input and output paths to be full paths
                                                                                                                                                                                                                                                                                                                                                                                          inputSearchDir=`makeFullPath "$inputSearchDir"`
                                                                                                                                                                                                                                                                                                                                                                                          outputDir=`makeFullPath "$outputDir"`

                                                                                                                                                                                                                                                                                                                                                                                          # see if the output directory needs to be created
                                                                                                                                                                                                                                                                                                                                                                                          if [ ! -e $outputDir ]; then
                                                                                                                                                                                                                                                                                                                                                                                              mkdir -p "$outputDir"
                                                                                                                                                                                                                                                                                                                                                                                            fi

                                                                                                                                                                                                                                                                                                                                                                                            # sanity checks
                                                                                                                                                                                                                                                                                                                                                                                            if [[ ! -x $toolPath || ! -d $inputSearchDir || ! -d $outputDir || -z "$toolArgs" ]]; then
                                                                                                                                                                                                                                                                                                                                                                                                displayUsageExit
                                                                                                                                                                                                                                                                                                                                                                                              fi

                                                                                                                                                                                                                                                                                                                                                                                              # display the basic setup information
                                                                                                                                                                                                                                                                                                                                                                                              echo "$scriptName $scriptVers"
                                                                                                                                                                                                                                                                                                                                                                                              echo "  Start: `date`"
                                                                                                                                                                                                                                                                                                                                                                                              echo "  Input directory: $inputSearchDir"
                                                                                                                                                                                                                                                                                                                                                                                              echo "  Output directory: $outputDir"
                                                                                                                                                                                                                                                                                                                                                                                              echo "  File type: $fileType"
                                                                                                                                                                                                                                                                                                                                                                                              echo "  Minimum get track time: $minTrackTime mins"
                                                                                                                                                                                                                                                                                                                                                                                              echo "  Tool path: $toolPath"
                                                                                                                                                                                                                                                                                                                                                                                              echo "  Tool args: $toolArgs"
                                                                                                                                                                                                                                                                                                                                                                                              echo "  - - - - - - - - - - - - - - - -"

                                                                                                                                                                                                                                                                                                                                                                                              # find all the DVD videos in the input search directory tree
                                                                                                                                                                                                                                                                                                                                                                                              # spaces in file path temporarily become /008 and paths are separ with spaces
                                                                                                                                                                                                                                                                                                                                                                                              dvdTSVidList=`find "$inputSearchDir" -name VIDEO_TS -print0 | tr ' ' '\007' | tr '\000' ' '`

                                                                                                                                                                                                                                                                                                                                                                                              # process each DVD video found
                                                                                                                                                                                                                                                                                                                                                                                              for dvdTSDir in $dvdTSVidList
                                                                                                                                                                                                                                                                                                                                                                                              do
                                                                                                                                                                                                                                                                                                                                                                                                  # correct the tmp char back to spaces in the DVD file paths
                                                                                                                                                                                                                                                                                                                                                                                                    dvdTSDir=`echo $dvdTSDir | tr '\007' ' '`
                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                      # get the DVD's name and path to root of the DVD
                                                                                                                                                                                                                                                                                                                                                                                                        dvdVolPath=`dirname "$dvdTSDir"`
                                                                                                                                                                                                                                                                                                                                                                                                          dvdName=`basename "$dvdVolPath"`
                                                                                                                                                                                                                                                                                                                                                                                                            dvdNameALNUM=`basename "$dvdVolPath" | sed 's/[^[:alnum:]^-^_]//g'`
                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                              # display information
                                                                                                                                                                                                                                                                                                                                                                                                                echo "  * Processing DVD '$dvdName'"
                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                  # create tmp link to the dvdVolPath to workaround a problem that the
                                                                                                                                                                                                                                                                                                                                                                                                                    # HandBrakeCLI tool has a problem with the input file paths with space
                                                                                                                                                                                                                                                                                                                                                                                                                      # when in a script
                                                                                                                                                                                                                                                                                                                                                                                                                        tmpNoSpacePath="/tmp/dvdVol-$dvdNameALNUM-$scriptPID"
                                                                                                                                                                                                                                                                                                                                                                                                                          ln -s "$dvdVolPath" $tmpNoSpacePath
                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                            # get the track list information from the DVD
                                                                                                                                                                                                                                                                                                                                                                                                                              cmd="$toolPath -i $tmpNoSpacePath $toolTrackArgs /dev/null 2>&1"
                                                                                                                                                                                                                                                                                                                                                                                                                                dvdTrackInfo=`eval $cmd`
                                                                                                                                                                                                                                                                                                                                                                                                                                  # save the DVD info
                                                                                                                                                                                                                                                                                                                                                                                                                                    outputFilePath="$outputDir/${dvdName}_Info.txt"
                                                                                                                                                                                                                                                                                                                                                                                                                                      if [ $saveDVDinfo -eq 1 ]; then
                                                                                                                                                                                                                                                                                                                                                                                                                                            if [[ ! -e  $outputFilePath || skipDuplicates -eq 0 ]]; then
                                                                                                                                                                                                                                                                                                                                                                                                                                                    echo "$dvdTrackInfo" | egrep '[ \t]*\+' > "$outputFilePath"
                                                                                                                                                                                                                                                                                                                                                                                                                                                        fi
                                                                                                                                                                                                                                                                                                                                                                                                                                                          fi
                                                                                                                                                                                                                                                                                                                                                                                                                                                            # get the track number of tracks which are longer then the time desired
                                                                                                                                                                                                                                                                                                                                                                                                                                                              trackFetchList=`getTrackListLongerThan $minTrackTime "$dvdTrackInfo"`
                                                                                                                                                                                                                                                                                                                                                                                                                                                                if [ ! -z "$trackFetchList" ];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    then
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          echo "   Will encode the following tracks: `echo $trackFetchList | sed 's/ /, /g'` "
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            else
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  echo "   No tracks on this DVD are longer then the minimum track time setting"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    fi
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      trackCount=`echo $trackFetchList | wc -w`
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        for aTrack in $trackFetchList
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            do
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  if [ $trackCount -gt 1 ]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          then outputFilePath="$outputDir/${dvdName}${aTrack}$fileType"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  else outputFilePath="$outputDir/${dvdName}$fileType"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        fi
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            cmd="$toolPath -i $tmpNoSpacePath $toolArgs -t $aTrack -o \"$outputFilePath\" > /tmp/${dvdNameALNUM}Results.txt 2>&1"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if [[ ! -e  $outputFilePath || skipDuplicates -eq 0 ]];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      then
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              # simple command execution
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    #ripResult=`eval $cmd`
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          # background command execution with some status
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                eval $cmd &
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      cmdPID=$!
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            while [ `isPIDRunning $cmdPID` -eq 1 ]; do
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      cmdStatusTxt="`tail -n 1 /tmp/${dvdNameALNUM}Results.txt | grep 'Encoding: '`"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              if [ ! -z "$cmdStatusTxt" ]; then
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          echo -n "$cmdStatusTxt"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  fi
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          sleep 1s
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                done
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      echo ""
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            wait $cmdPID
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                else
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        echo "   Output file SKIPPED because it ALREADY EXISTS"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            fi
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if [ -e /tmp/${dvdNameALNUM}Results.txt ]; then
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        rm /tmp/${dvdNameALNUM}Results.txt
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            fi
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              done

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                rm $tmpNoSpacePath
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              done

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              echo "  - - - - - - - - - - - - - - - -"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              echo "  End: `date`"

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              exit 0


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              # End Script
